package es.unileon.ulebank.assets.domain;

// Generated Jun 15, 2014 6:36:38 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FeeCases generated by hbm2java
 */
@Entity
@Table(name = "FEE_CASES", catalog = "ULEBANK_FINAL")
public class FeeCases implements java.io.Serializable {

	private Integer feeCaseId;
	private LiquidationFee liquidationFee;
	private String amountFormula;
	private String triggeringConditions;
	private String subject;

	public FeeCases() {
	}

	public FeeCases(LiquidationFee liquidationFee, String amountFormula,
			String triggeringConditions, String subject) {
		this.liquidationFee = liquidationFee;
		this.amountFormula = amountFormula;
		this.triggeringConditions = triggeringConditions;
		this.subject = subject;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "fee_case_id", unique = true, nullable = false)
	public Integer getFeeCaseId() {
		return this.feeCaseId;
	}

	public void setFeeCaseId(Integer feeCaseId) {
		this.feeCaseId = feeCaseId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "liquidation_fee_id", nullable = false)
	public LiquidationFee getLiquidationFee() {
		return this.liquidationFee;
	}

	public void setLiquidationFee(LiquidationFee liquidationFee) {
		this.liquidationFee = liquidationFee;
	}

	@Column(name = "amount_formula", nullable = false, length = 256)
	public String getAmountFormula() {
		return this.amountFormula;
	}

	public void setAmountFormula(String amountFormula) {
		this.amountFormula = amountFormula;
	}

	@Column(name = "triggering_conditions", nullable = false, length = 256)
	public String getTriggeringConditions() {
		return this.triggeringConditions;
	}

	public void setTriggeringConditions(String triggeringConditions) {
		this.triggeringConditions = triggeringConditions;
	}

	@Column(name = "subject", nullable = false)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

}
