package es.unileon.ulebank.assets.domain;

// Generated Jun 15, 2014 6:36:38 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * InvestmentAccounts generated by hbm2java
 */
@Entity
@Table(name = "INVESTMENT_ACCOUNTS", catalog = "ULEBANK_FINAL")
public class InvestmentAccounts implements java.io.Serializable {

	private long investmentAccountId;
	private String clientId;
	private String accountId;
	private long buyStockageFee;
	private long sellStockageFee;
	private long transactionHistory;

	public InvestmentAccounts() {
	}

	public InvestmentAccounts(long investmentAccountId, String clientId,
			String accountId, long buyStockageFee, long sellStockageFee,
			long transactionHistory) {
		this.investmentAccountId = investmentAccountId;
		this.clientId = clientId;
		this.accountId = accountId;
		this.buyStockageFee = buyStockageFee;
		this.sellStockageFee = sellStockageFee;
		this.transactionHistory = transactionHistory;
	}

	@Id
	@Column(name = "investmentAccountID", unique = true, nullable = false)
	public long getInvestmentAccountId() {
		return this.investmentAccountId;
	}

	public void setInvestmentAccountId(long investmentAccountId) {
		this.investmentAccountId = investmentAccountId;
	}

	@Column(name = "clientID", nullable = false, length = 32)
	public String getClientId() {
		return this.clientId;
	}

	public void setClientId(String clientId) {
		this.clientId = clientId;
	}

	@Column(name = "accountID", nullable = false, length = 32)
	public String getAccountId() {
		return this.accountId;
	}

	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	@Column(name = "buyStockageFee", nullable = false)
	public long getBuyStockageFee() {
		return this.buyStockageFee;
	}

	public void setBuyStockageFee(long buyStockageFee) {
		this.buyStockageFee = buyStockageFee;
	}

	@Column(name = "sellStockageFee", nullable = false)
	public long getSellStockageFee() {
		return this.sellStockageFee;
	}

	public void setSellStockageFee(long sellStockageFee) {
		this.sellStockageFee = sellStockageFee;
	}

	@Column(name = "transactionHistory", nullable = false)
	public long getTransactionHistory() {
		return this.transactionHistory;
	}

	public void setTransactionHistory(long transactionHistory) {
		this.transactionHistory = transactionHistory;
	}

}
