package es.unileon.ulebank.assets.domain;

// Generated Jun 15, 2014 6:36:38 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import es.unileon.ulebank.account.Accounts;

/**
 * LiquidationFee generated by hbm2java
 */
@Entity
@Table(name = "LIQUIDATION_FEE", catalog = "ULEBANK_FINAL")
public class LiquidationFee implements java.io.Serializable {

	private Integer liquidationFeeId;
	private Accounts accounts;
	private Set<FeeCases> feeCaseses = new HashSet<FeeCases>(0);

	public LiquidationFee() {
	}

	public LiquidationFee(Accounts accounts) {
		this.accounts = accounts;
	}

	public LiquidationFee(Accounts accounts, Set<FeeCases> feeCaseses) {
		this.accounts = accounts;
		this.feeCaseses = feeCaseses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "liquidation_fee_id", unique = true, nullable = false)
	public Integer getLiquidationFeeId() {
		return this.liquidationFeeId;
	}

	public void setLiquidationFeeId(Integer liquidationFeeId) {
		this.liquidationFeeId = liquidationFeeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "account_number", nullable = false)
	public Accounts getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Accounts accounts) {
		this.accounts = accounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "liquidationFee")
	public Set<FeeCases> getFeeCaseses() {
		return this.feeCaseses;
	}

	public void setFeeCaseses(Set<FeeCases> feeCaseses) {
		this.feeCaseses = feeCaseses;
	}

}
