package es.unileon.ulebank.assets.domain;

// Generated Jun 15, 2014 6:36:38 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pack generated by hbm2java
 */
@Entity
@Table(name = "PACK", catalog = "ULEBANK_FINAL")
public class Pack implements java.io.Serializable {

	private Integer id;
	private String productId;
	private String accountNumber;
	private long amount;
	private Double price;
	private Date date;
	private char discriminartor;

	public Pack() {
	}

	public Pack(String productId, String accountNumber, long amount,
			char discriminartor) {
		this.productId = productId;
		this.accountNumber = accountNumber;
		this.amount = amount;
		this.discriminartor = discriminartor;
	}

	public Pack(String productId, String accountNumber, long amount,
			Double price, Date date, char discriminartor) {
		this.productId = productId;
		this.accountNumber = accountNumber;
		this.amount = amount;
		this.price = price;
		this.date = date;
		this.discriminartor = discriminartor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "product_id", nullable = false, length = 64)
	public String getProductId() {
		return this.productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	@Column(name = "account_number", nullable = false, length = 64)
	public String getAccountNumber() {
		return this.accountNumber;
	}

	public void setAccountNumber(String accountNumber) {
		this.accountNumber = accountNumber;
	}

	@Column(name = "amount", nullable = false)
	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	@Column(name = "price", precision = 22, scale = 0)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "discriminartor", nullable = false, length = 1)
	public char getDiscriminartor() {
		return this.discriminartor;
	}

	public void setDiscriminartor(char discriminartor) {
		this.discriminartor = discriminartor;
	}

}
